### PR TITLE
Add important priority packages that we actually want so we can

### PR DESCRIPTION
**Pull request by BryanQuigley**
drop the others.

Backstory: https://community.endlessos.com/t/xterm-shows-in-3-10/16322/11

### CODE REVIEW

**Comment by dbnicholson** [comment]
ok to test

**Comment by dbnicholson** [comment]
Based on your analysis, I think you should add dmidecode, procps, systemd and fdisk. In the case of systemd, I think it's an oversight that it's not in there already. Even though it will come in via systemd-sysv, I'd rather explicitly say systemd is there in case debian wants to shuffle around the packages. The rest are utilities I'd want to ensure were available, and I'd rather be explicit about it than implicit.

**Comment by BryanQuigley** [comment]
Sure, Added.

**Review by dbnicholson — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
