### PR TITLE
Prefer Text Editor to gedit for text files

### PR DESCRIPTION
**Pull request by wjt**
https://phabricator.endlessm.com/T32962

### CODE REVIEW

**Review by manuq — COMMENTED** [review]
Noob question: How does this `debian/endless-mimeapps.list` work with the `/usr/share/applications/gnome-mimeapps.list` installed in EOS?

**Comment by wjt** [comment]
I believe it is selected based on the `XDG_CURRENT_DESKTOP` environment variable but, honestly, I have no idea

**Comment by wjt** [comment]
I'm correct! https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-latest.html

**Comment by manuq** [comment]
> I'm correct! https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-latest.html

Great, which normally in EOS is:
```
$ echo $XDG_CURRENT_DESKTOP
Endless:GNOME
```

**Review by dylanmccall — APPROVED** [review]

**Pull request merged**
