### PR TITLE
core-depends: add buildah

### PR DESCRIPTION
**Pull request by andrunko**
https://phabricator.endlessm.com/T26404

### CODE REVIEW

**Comment by andrunko** [comment]
The Jenkins failure is because the pkg was not integrated yet - see phab task for details on OBS MR.

**Comment by wjt** [comment]
test this please

[here's documentation on the commands Jenkins understands](https://phabricator.endlessm.com/w/software/build/ci-integration/#pull-requests)

**Comment by wjt** [comment]
Doh, now it's broken because master is broken due to shell 3.32 and family landing. :)

**Comment by ramcq** [comment]
test this please

**Pull request merged**
